baseurl = "https://zhangyadong.me/"

title = "Mai"

theme = ["hugo-search-fuse-js" , "hugo-onyx-theme"]

enableGitInfo = true

disableFastRender = true        # Hugo 0.30

pygmentsCodeFences = true       # This applies to Chroma too.
pygmentsUseClasses = true       # This applies to Chroma too.

enableEmoji = true

[Author]
  name = "Mai"

[params]
  name = "Eorg"
  description = "A Paper Typesetting Editor"

  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  dateform = "Mon Jan 2, 2006"

  github_user = "zhyd1997"
  github_repo = "Eorg"
  github_banner = true

#  images = ["/favicon-196x196.png"] # Used in twitter_cards.html partial

  custom_css = [ # Chroma GitHub theme
                 "css/github_chroma.css" # Needs pygmentsUseClasses to be true
               ]
  custom_css_absolute = [ # Iosevka fonts
                          # "https://cdn.rawgit.com/kaushalmodi/iosevka-mirror/v1.13.2/iosevka.css"
                        ]
  custom_js  = []

  favicon = "favicon.ico"

[params.source]
  url = "https://zhangyadong.me/"
  org_dir = "docs"

[params.sidebar]
  logo = "favicon-256x256.png"

  github_button  = true
  travis_button  = false
  codecov_button = false
  gratipay = ""

  # Mon Sep 04 23:55:36 EDT 2017 - kmodi
  # Disable this option for now.. but seems to be useful in future
  show_relations = false

[params.footer]
  copyright = ""
  show_powered_by = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
